# Generated by Django 5.0.7 on 2024-07-18 15:16

import django.core.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_alter_inventoryitem_quantity_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='inventoryitem',
            name='Quantity_Value_Valid',
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='price_per_unit',
            field=models.PositiveSmallIntegerField(default=0.0, validators=[django.core.validators.MinValueValidator(0)]),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='inventoryitem',
            constraint=models.CheckConstraint(check=models.Q(('quantity__gte', 0)), name='quantity_value_valid', violation_error_message='Quantity invalid: cannot be less than 0'),
        ),
        migrations.AddConstraint(
            model_name='inventoryitem',
            constraint=models.CheckConstraint(check=models.Q(('price_per_unit__gte', 0)), name='price_value_valid', violation_error_message='Price invalid: cannot be less than 0'),
        ),
    ]
