# Generated by Django 5.0.7 on 2024-07-18 15:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_remove_inventoryitem_quantity_value_valid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryitem',
            name='price_per_unit',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
